# This is a basic workflow to help you get started with Actions

name: Continuos Integration

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Static_Analysis:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Check Misra C
        run: docker run --rm -v ${PWD}:/src facthunder/cppcheck:latest cppcheck src/ --addon=misra.py --enable=all --include=include/ --suppress=unusedFunction --inline-suppr --error-exitcode=1

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build the examples folder
        run: docker run --rm -v $PWD:/W25N01GVxxIG -w /W25N01GVxxIG espressif/idf:release-v4.4 /bin/sh -c "cd examples && idf.py build"
        
  Unit_test_without_Build:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
            
      - name: inspect log
        run: cat examples/test/report.xml
            
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
            files: examples/test/report.xml
